"""Update database schema

Revision ID: 712fe5b20657
Revises: 
Create Date: 2025-08-02 23:18:39.755717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '712fe5b20657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('chunk_count', sa.String(length=20), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='对话ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色'),
    sa.Column('message_type', sa.String(length=20), nullable=True, comment='消息类型'),
    sa.Column('message_metadata', sa.JSON(), nullable=True, comment='消息元数据'),
    sa.Column('tokens', sa.Integer(), nullable=True, comment='token数量'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('conversations', sa.Column('status', sa.String(length=50), nullable=True, comment='对话状态'))
    op.add_column('document_chunks', sa.Column('document_id', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('start_char', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_char', sa.Integer(), nullable=True))
    op.alter_column('document_chunks', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.add_column('knowledge_bases', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('knowledge_bases', sa.Column('document_count', sa.String(length=20), nullable=True))
    op.add_column('knowledge_bases', sa.Column('total_size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'total_size')
    op.drop_column('knowledge_bases', 'document_count')
    op.drop_column('knowledge_bases', 'is_public')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.alter_column('document_chunks', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('document_chunks', 'end_char')
    op.drop_column('document_chunks', 'start_char')
    op.drop_column('document_chunks', 'document_id')
    op.drop_column('conversations', 'status')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
